### ISSUE TITLE
Tratar exceção quando porto de interesse não está na tabela de portos.

### ISSUE THREAD

**Issue by sergiosilvar** [srodriguex/crawler_marine_traffic#10]

**Comment by Cmndll** [comment]
era bom detalhar o problema não ?

**Comment by sergiosilvar** [comment]
A exceção agora é tratada. 
1) Primeiro verifica se o arquivo de portos de interesse existe. Caso não exista, avisa o erro e o programa encerra.
2) Segundo, verifica se o arquivo de portos do brasil do crawling existe. Caso não exista, avisa o erro e o programa sai.
3) Terceiro, verifica se cada porto de interesse consta no arquivo de portos do Brasil. Caso não conste, avisa como um alerta e o programa não encerra, mas passa para o próximo porto de interesse.

**Comment by sergiosilvar** [comment]
Resolvido pelo commit afb75c4.
