### ISSUE TITLE
Retornar informações de navios 

### ISSUE THREAD

**Issue by Cmndll** [srodriguex/crawler_marine_traffic#11]
Criar uma tabela, que seja incremental, que traga informações dos navios 
IMO; MMSI; CALL SIGN; FLAG; TYPE; GROSS TONNAGE; DEADWEIGHT; LENGHT OVERALL x BREATH EXTREME; YEAR BUILT; STATUS

Estas informações devem ser dos navios que estiverem na pesquisa de navios em tanques e navios previstos para chegada em porto.

**Comment by sergiosilvar** [comment]
Resolvido em 26f1391.
