### ISSUE TITLE
Tratamento do Proxy

### ISSUE THREAD

**Issue by Cmndll** [srodriguex/crawler_marine_traffic#17]
ao executar o programa, o mesmo exige sempre a exceução do proxy, mesmo em locais que não sejam necessarios este tratamento.
winError10061 nenhuma conexao pode ser feita.....

**Comment by sergiosilvar** [comment]
@Cmndll , como o script é mais utilizado em ambiente com proxy, a chamada "python marine_traffic_crawler.py" executa automaticamente o proxy. 

Para executar sem o proxy, coloque qualquer argumento depois do nome do script. Por exemplo:  "python marine_traffic_crawler.py **noproxy**". Pode ser qualquer palavra depois do nome do script, não necessariamente noproxy.

**Comment by sergiosilvar** [comment]
Já resolvido. Para não usar o proxy ptbrs, basta colocar qq palavra depois do nome do script na chamada na linha de comando.
