### ISSUE TITLE
retornar a capacidade do navio 

### ISSUE THREAD

**Issue by Cmndll** [srodriguex/crawler_marine_traffic#2]
retornar a capacidade do navio no arquivo chegada_prevista.csv

**Comment by sergiosilvar** [comment]
Isso fará com que a consulta fique muito lenta pois irá fazer um request de cada navio.
Já não serve as informações do navio na tabela de navios?

**Comment by Cmndll** [comment]
Não.
A lentidão depende dos olhos de quem ver. Pode demorar 2horas, desde que não seja feita manualmente. Ontem cadastrei todos os 167 navios. Demorou umas duas horas.

**Comment by Cmndll** [comment]
pelo que entendi isso ficou implementado certo ?

**Comment by sergiosilvar** [comment]
Sim, já foi resolvido em no commit 26f1391.
