### ISSUE TITLE
Tratamento de Erros - Tópico para registro de Erros e Ajustres

### ISSUE THREAD

**Issue by Cmndll** [srodriguex/crawler_marine_traffic#21]
Após rodar a aplicação informando o argumento de proxy a rotina  crawl_portos_brasil, funcionou e gerou a leitura dos portos.
Erro que ocorreu -----------------------------------------------------------------------------
 File "marine_traffic_crawler.py", line 527, in <module>
   crawl_navios_em_portos(proxy = proxies)
 File "marine_traffic_crawler.py", line 247, in crawl_navios_em_portos
   url_navios_porto = URL_BASE + porto.LinkNaviosPorto.values[0]
ndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by sergiosilvar** [comment]
Baixe a versão do commit afb75c4 (ou da [página principal](https://github.com/srodriguex/crawler_marine_traffic), pois os próximos commits já conterão esse). Acabo de testar aqui sem nenhum problema. Esse commit já trata de exceção especificada em #10.

**Comment by sergiosilvar** [comment]
Se o erro continuar, posta aqui para eu verificar.
