### ISSUE TITLE
Coletar todos os tipos de portos

### ISSUE THREAD

**Issue by Cmndll** [srodriguex/crawler_marine_traffic#22]
Após cruzar informações de relatórios diferentes, observado que alguns navios não apareciam no relatórios de navios em portos, nem em expectativa de entrega.

Verificado que há navios que estão ancorados no porto que é diferente de estar no porto e o marine traffic classifica como tipo Anchorage.

Desta forma na coleta não pode filtrar o tipo do porto, devem ser carregados todos os tipos e colocado na lista csv o tipo para poder analisar cada situação.

temos : navios em portos, navios ancorados e navios com previsao de chagada.

no caso do navios em portos e ancorados o arquivo pode manter o mesmo (navios_em_portos.csv) mas com uma coluna a mais com o tipo de porto.

**Comment by sergiosilvar** [comment]
O algoritmo já pegava o tipo do porto. O que antes era redundante, agora será usado. Basta apenas mudar a URL pois o filtro era feito nela.
Entretanto, o busca de navios é somente para os portos de interesse. Portanto deve-se atualizar esse arquivo com os ancoradouros de interesse.

**Comment by sergiosilvar** [comment]
Além de resolver #22, o commit associado também permite esconder" um porto de interesse, para teste por exemplo. Para tal basta colocar o caractere # na frente que o algoritmo ignorará o porto de interesse .
