### ISSUE TITLE
converter ponto decimal para vírgula nos campos lat/long devido ao consumo no MS Excel em pt-br

### ISSUE THREAD

**Issue by sergiosilvar** [srodriguex/crawler_marine_traffic#5]

**Comment by sergiosilvar** [comment]
Resolvido @Cmndll.

**Comment by Cmndll** [comment]
Ajustar o campo longitude. No caso do arquivo de entregas previstas ficou positivo. Não vi os demais Ainda.

**Comment by sergiosilvar** [comment]
Verifique novamente. Caso esteja ok, feche a issue.
